name: Deploy HTML to GitHub Pages

on:
  push:
    branches: [ main ]
jobs:
    deploy:
        runs-on: ubuntu-latest    
        steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Log in to Docker Hub
           run: echo "${{ 'SSss17812984' }}" | docker login -u "${{ 'saraRashidiyan' }}" --password-stdin

         - name: Build Docker image
           run: docker build -t saraRashidiyan/html-site .

         - name: Push image to Docker Hub
           run: docker push saraRashidiyan/html-site

           